cmake_minimum_required(VERSION 3.16)

project(cpp_semester_2_14_06_22_2026_min_product_table_main LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(cpp_semester_2_14_06_22_2026_min_product_table_main
    "CMakeFiles/4.3.2/CompilerIdCXX/apple-sdk.cpp"
    "CMakeFiles/4.3.2/CompilerIdCXX/CMakeCXXCompilerId.cpp"
    "main.cpp"
    "Product.cpp"
)
